### ISSUE TITLE
[chat] refactor strategy class with booster api

### ISSUE THREAD

**Issue by CWHer** [hpcaitech/ColossalAI#3978]
## Description

There are 4 existing strategies implemented in `coati/strategies/...`.
The issue aims to refactor `DDPStrategy` and `ColossalAIStrategy` classes with the new booster API.

## TODOs
- [x] Refactor base `Strategy` class with booster API.
- [x] Refactor `NaiveStrategy` class using `plugin=None`.
- [x] Refactor `DDPStrategy` class using `TorchDDPPlugin`.
- [x] Refactor `ColossalAIStrategy` class using `GeminiPlugin`, `LowLevelZeroPlugin`.
