### ISSUE TITLE
[chat] use official transformers and fix some errors

### ISSUE THREAD

**Issue by CWHer** [hpcaitech/ColossalAI#4116]
## Description

As reported in https://github.com/hpcaitech/ColossalAI/issues/4023, some use cases of `train_prompts` would fail.

We would like to adopt the following methods to try to fix them.

## TODOs

- [x] Upgrade the version of `transformers` that `coati` depends on to the latest version (i.e., official version).
- [x] Fix errors of `llama` model.
- [x] Remove `deberta` and `roberta` support as less used and still buggy.
