### ISSUE TITLE
[chat] add unit tests

### ISSUE THREAD

**Issue by CWHer** [hpcaitech/ColossalAI#4133]
## Description

Currently, `Coati` only has a few unit tests and integration tests. Thus, some parts of `coati` are not covered and may be buggy. This issue aims to add more unit tests, both from the system perspective and the algorithm perspective, for them.

The file structure of `Coati` is as follows,
<img width="315" alt="image" src="https://github.com/hpcaitech/ColossalAI/assets/31888981/84907ead-3c1e-4d32-acb7-cb9e87fc332b">

We will test each of them iteratively.

## TODOs

- [x] Excluded files and directories are
  ```bash
  evaluate/*
  inference/*
  coati/ray/*
  coati/kernels/*
  coati/quant/*
  examples/ray/*
  examples/community/*
  benchmarks/ray/*
  ```
- [x] Update ci/cd actions accordingly.
- Test `coati/`
  - [x] Test `dataset/`
  - [x] Test `models/`
  - [x] Test `experience_buffer/`
  - [x] Test `experience_maker/`
  - [x] Test `trainer/`
- [x] Test `examples/`
- [x] Test `benchmarks/`
